<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
            CREATE TABLE orders (
                id                     uuid         PRIMARY KEY DEFAULT uuidv7(),
                order_number           bigint       NOT NULL UNIQUE,
                customer_id            uuid         NOT NULL,
                customer_name          varchar(120) NOT NULL,
                customer_email         varchar(254) NOT NULL,
                status                 varchar(24)  NOT NULL CHECK (status IN (
                                           'pending_payment', 'paid', 'shipped', 'delivered', 'cancelled', 'returned')),
                fulfillment_center     char(4)      NOT NULL REFERENCES fulfillment_centers (code),
                ship_street            varchar(160) NOT NULL,
                ship_number            varchar(16)  NOT NULL,
                ship_complement        varchar(80),
                ship_district          varchar(80)  NOT NULL,
                ship_city              varchar(80)  NOT NULL,
                ship_state             char(2)      NOT NULL CHECK (ship_state ~ '^[A-Z]{2}$'),
                ship_postal_code       char(8)      NOT NULL CHECK (ship_postal_code ~ '^[0-9]{8}$'),
                ship_latitude          numeric(9,6) CHECK (ship_latitude BETWEEN -90 AND 90),
                ship_longitude         numeric(9,6) CHECK (ship_longitude BETWEEN -180 AND 180),
                total_cents            bigint       NOT NULL CHECK (total_cents >= 0),
                currency               char(3)      NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
                reservation_expires_at timestamptz  NOT NULL,
                placed_at              timestamptz  NOT NULL,
                updated_at             timestamptz  NOT NULL,
                version                integer      NOT NULL DEFAULT 1 CHECK (version > 0)
            );

            CREATE INDEX orders_customer_idx ON orders (customer_id, placed_at DESC);
            -- The expiry job only ever looks at unpaid orders: a partial index keeps it tiny.
            CREATE INDEX orders_awaiting_payment_idx ON orders (reservation_expires_at) WHERE status = 'pending_payment';

            COMMENT ON COLUMN orders.id IS 'UUIDv7 generated by the domain; the default is only a safety net.';
            COMMENT ON COLUMN orders.order_number IS 'Public Snowflake number (datacenter 1, workers 1-2).';
            COMMENT ON COLUMN orders.status IS 'Order state machine; see docs/architecture/state-machines.md.';

            CREATE TABLE order_lines (
                order_id         uuid         NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
                line_number      smallint     NOT NULL CHECK (line_number > 0),
                sku              varchar(32)  NOT NULL,
                product_name     varchar(160) NOT NULL,
                quantity         integer      NOT NULL CHECK (quantity BETWEEN 1 AND 10),
                unit_price_cents bigint       NOT NULL CHECK (unit_price_cents >= 0),
                PRIMARY KEY (order_id, line_number)
            );

            COMMENT ON COLUMN order_lines.unit_price_cents IS 'Price frozen when the order was placed.';

            CREATE TABLE order_status_transitions (
                id          uuid         PRIMARY KEY DEFAULT uuidv7(),
                order_id    uuid         NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
                from_status varchar(24),
                to_status   varchar(24)  NOT NULL,
                reason      varchar(120),
                occurred_at timestamptz  NOT NULL
            );

            CREATE INDEX order_status_transitions_order_idx ON order_status_transitions (order_id, occurred_at);

            COMMENT ON TABLE order_status_transitions IS 'Append-only history of the order state machine.';
        SQL);
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE order_status_transitions, order_lines, orders');
    }
};
